"""Typed errors for the multi-cli-delivery core. All escalate to the human."""
from __future__ import annotations

class McdError(Exception):
    """Base for every multi-cli-delivery failure Control must surface."""

class ConfigError(McdError): ...
class HandoffError(McdError): ...
class ContainmentError(McdError): ...
class DispatchError(McdError): ...
class PreflightError(McdError): ...
